### ISSUE TITLE
Footer bugs

### ISSUE THREAD

**Issue by LibbyUX** [hubmapconsortium/hra-ui#527]
Hi team, submitting bugs for our two new UIs:

### CDE:
- [ ] The footer content needs to be centered responsively when the page expands. Currently it is left aligned.

Note: The CDE footer could be fixed responsively first, then implemented in Dashboards and globally in our UIs. The fonts and buttons are perfect, but we just need that responsiveness for it to be 100%

### Dashboards:
- [ ] The social buttons are invisible but I can access them on hover
- [ ] The Funded By icons are too large

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/e1058f0d-47c9-4f3e-8045-fa08842bb801)

![image](https://github.com/hubmapconsortium/hra-ui/assets/97060856/89c09309-9dac-48b8-ac0c-e57b6076096b)

**Comment by bhushankhope** [comment]
Fixed this in PR #528

**Comment by LibbyUX** [comment]
Thank you @bhushankhope ! I cleared my browsing data right now and hard refreshed. I'm still seeing the old footers. Maybe it's taking a little longer to update? I appreciate you knocking this out so fast!

<img width="1645" alt="Screenshot 2024-07-09 at 9 27 06 AM" src="https://github.com/hubmapconsortium/hra-ui/assets/97060856/7f4f12af-d842-4c4f-ae4a-afb36aed6479">

**Comment by LibbyUX** [comment]
It's perfect and I approve! I will close this issue when the updates are live. Thanks so much, @bhushankhope !
